name: 'shortnr-local'
services:
  web:
    build: ./shortnr-client
    image: shortnr/web
    container_name: shortnr-web
    ports:
      - "4200:4200"
    profiles: ["frontend"]

  api:
    build:
      context: ./shortnr-service
      dockerfile: Dockerfile.local
    image: shortnr/api
    container_name: shortnr-api
    depends_on:
      - cache
      - database
    ports:
      - "5120:8080"
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORT=8080
      - AWS_ACCESS_KEY_ID=FAKEAWSKEYID
      - AWS_SECRET_ACCESS_KEY=FAKEAWSSECRETKEY
      - AWS_REGION=eu-west-1

  cache:
    image: redis:7.2.3-alpine3.19
    container_name: shortnr-cache
    ports:
      - "6379:6379"
    volumes:
      - shortnr-cache-data:/data
    restart: always

  database:
    image: amazon/dynamodb-local:2.2.0
    container_name: shortnr-database
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    user: root
    ports:
      - "8000:8000"
    volumes:
      - shortnr-database-data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal

networks:
  default:
    name: shortnr_default

volumes:
  shortnr-database-data:
  shortnr-cache-data:

